name: my_souaq
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  provider: ^6.0.5
  shared_preferences: ^2.0.18
  badges: ^3.0.2
  carousel_slider: ^4.2.1
  dotted_border: ^2.0.0+3
  file_picker: ^5.2.6
  cloudinary_public: ^0.20.0
  flutter_speed_dial: ^6.2.0
  flutter_rating_bar: ^4.0.1
  pay: ^1.1.0
  charts_flutter: ^0.12.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true
  assets:
    - assets/images/
    - assets/gpay.json
    - assets/applepay.json

  # To add assets to your application, add an assets section, like this:
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
